package com.paperloong.lux.ui.theme

import androidx.compose.ui.graphics.Color

/**
 *
 *
 * @author WangZhiYao
 * @since 2024/4/23
 */
val primaryLight = Color(0xFF00572F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF207F4C)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF45664E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC9EED0)
val onSecondaryContainerLight = Color(0xFF30503A)
val tertiaryLight = Color(0xFF2C4792)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF536CB9)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FBF3)
val onBackgroundLight = Color(0xFF181D19)
val surfaceLight = Color(0xFFF6FBF3)
val onSurfaceLight = Color(0xFF181D19)
val surfaceVariantLight = Color(0xFFDAE6D9)
val onSurfaceVariantLight = Color(0xFF3F4941)
val outlineLight = Color(0xFF6F7A70)
val outlineVariantLight = Color(0xFFBEC9BE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D322D)
val inverseOnSurfaceLight = Color(0xFFEEF2EB)
val inversePrimaryLight = Color(0xFF7FD99D)
val surfaceDimLight = Color(0xFFD7DBD4)
val surfaceBrightLight = Color(0xFFF6FBF3)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5EE)
val surfaceContainerLight = Color(0xFFEBEFE8)
val surfaceContainerHighLight = Color(0xFFE5E9E2)
val surfaceContainerHighestLight = Color(0xFFDFE4DD)

val primaryDark = Color(0xFF7FD99D)
val onPrimaryDark = Color(0xFF00391D)
val primaryContainerDark = Color(0xFF0F7543)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFABCFB3)
val onSecondaryDark = Color(0xFF173722)
val secondaryContainerDark = Color(0xFF24442F)
val onSecondaryContainerDark = Color(0xFFB5DABD)
val tertiaryDark = Color(0xFFB4C4FF)
val onTertiaryDark = Color(0xFF072A75)
val tertiaryContainerDark = Color(0xFF4962AE)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101511)
val onBackgroundDark = Color(0xFFDFE4DD)
val surfaceDark = Color(0xFF101511)
val onSurfaceDark = Color(0xFFDFE4DD)
val surfaceVariantDark = Color(0xFF3F4941)
val onSurfaceVariantDark = Color(0xFFBEC9BE)
val outlineDark = Color(0xFF889489)
val outlineVariantDark = Color(0xFF3F4941)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE4DD)
val inverseOnSurfaceDark = Color(0xFF2D322D)
val inversePrimaryDark = Color(0xFF006D3C)
val surfaceDimDark = Color(0xFF101511)
val surfaceBrightDark = Color(0xFF353A36)
val surfaceContainerLowestDark = Color(0xFF0A0F0B)
val surfaceContainerLowDark = Color(0xFF181D19)
val surfaceContainerDark = Color(0xFF1C211D)
val surfaceContainerHighDark = Color(0xFF262B27)
val surfaceContainerHighestDark = Color(0xFF313631)
